import { Novedad } from './../../novedades/mock-data/novedad';

export const NOVEDADES: Novedad[] = [
    {
        id: 1563513,
        titulo: 'Se realizó el primer taller de vocabularios controlados de Salud',
        bajada: 'Fue dirigida a miembros de equipos de salud de las distintas zonas sanitarias de la provincia.',
        imagen: [
            'https://innovadores.larazon.es/uploads/innovadores/noticias/n-a-1580318603.jpg',
            'https://miro.medium.com/max/1600/1*6jHfGiyWLiks_i5iU1tOhw.jpeg',
            'https://ui.andes.gob.ar/assets/img/homepage/andes-home-banner.jpg',
        ],

        nota: 'El día viernes 27 de Octubre, se llevó a cabo el Taller de Vocabularios Controlados y representación de significados en Salud. El taller se desarrollo en el Colegio Médico de Neuquén en el marco del proyecto ANDES y estuvo a cargo del Lic. Marcelo D. Carrascal, Jefe del Dto de Tecnologías de la Información del Hospital Castro Rendón. El objetivo del taller fue capacitar a profesionales de distintas especialidades en la utilización de SNOMED-CT, nomenclatura sistematizada de términos de medicina y terminología clínica. Dicha herramienta es la terminología de salud científicamente validad y más extensa del mundo. Permite la representación de conceptos de salud en forma consistente y procesable lo que la hace una herramienta excepcional para trabajar sobre registros electrónicos de salud. Implementada en aplicaciones de software, SNOMED-CT es utilizada para representar información de salud relevante en forma consistente. Provee una forma estandarizada de representar los conceptos de salud ingresados por los miembros del equipo y permite su interpretación automática a través de sistemas de validación y un vocabulario controlado semanticamente muy rico. En el taller, el primero de una serie de encuentros a realizarse en los próximos meses, participaron médicos, enfermeros, odontólogos y técnicos representando a la Zona 4, Zona Metropolitana, Hospital Castro Rendón, Direccion Provincial de Información Sanitaria entre otras. SNOMED-CT está próximo a ser incorporado como estándar nacional en los sistemas de registros electrónicos de salud. El proyecto ANDES incorpora SNOMED desde su concepción por lo que ya se ha empezado con la capacitación en su utilización.',
        categoria: 'mejora',
        fechaPublicacion: '03-02-2020',
        modulo: 'RUP',
        estado: true,
    },
    {
        id: 3515125,
        titulo: 'Se capacitó a personal perteneciente a efectores de la Zona Metro',
        bajada: 'La capacitación se realizó en el auditorio del Ministerio de Salud y fue orientada a representantes de cada efector de Zona Metro.',
        imagen: [
            'https://miro.medium.com/max/1600/1*6jHfGiyWLiks_i5iU1tOhw.jpeg',
            'https://cdn2.f-cdn.com/contestentries/1461068/3980988/5c278c3d00512_thumb900.jpg',
            'https://www.daslatalla.com/wp-content/uploads/2019/07/shutterstock_517390705-1050x600.jpg',
        ],
        nota: 'El Lunes 9 de este mes se brindó una capacitación destinada a efectores de la Zona Metro en el auditorio del Ministerio de Salud. La jornada, desarrollada en el marco de la implementación del proyecto ANDES, estuvo orientada a representantes de cada centro de salud de la zona y fue asistida por Alejandra Garcia y Alejandro Ojeda, coordinadores de zona metro de Gestión de pacientes.Durante la actividad, se recorrió todo el proceso que involucra CITAS (Centro Inteligente de Trámites de Acceso a la Salud), desde la planificación de agendas hasta la revisión, codificación y otorgamiento de turnos.De esta manera, los asistentes pudieron despejar dudas y trasladar las funcionalidades de esta herramienta a su trabajo diario a través de ejemplos prácticos.',
        categoria: 'importante',
        fechaPublicacion: '29-12-2019',
        modulo: 'TOP',
        estado: true,
    },
    {
        id: 1561563,
        titulo: 'Titulo de tercera noticia',
        bajada: 'Esta es la bajada de la nota, un texto que da una primera percepcion al lector',
        imagen: [
            'https://s3-prod.modernhealthcare.com/s3fs-public/styles/width_792/public/NEWS_180209906_AR_0_TICWBRGHYYHC.jpg',
            'https://cdn2.f-cdn.com/contestentries/1461068/3980988/5c278c3d00512_thumb900.jpg',
            'https://www.daslatalla.com/wp-content/uploads/2019/07/shutterstock_517390705-1050x600.jpg',
        ],
        nota: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi.',
        categoria: 'novedad',
        fechaPublicacion: '17-11-2019',
        modulo: 'MPI',
        estado: true,
    },
    {
        id: 1563513,
        titulo: 'Se realizó el primer taller de vocabularios controlados de Salud',
        bajada: 'Fue dirigida a miembros de equipos de salud de las distintas zonas sanitarias de la provincia.',
        imagen: [
            'https://ticsalutsocial.cat/wp-content/uploads/2018/03/mhealth.jpg',
            'https://ui.andes.gob.ar/assets/img/homepage/andes-home-banner.jpg',
            'https://cdn2.f-cdn.com/contestentries/1461068/3980988/5c278c3d00512_thumb900.jpg',
        ],

        nota: 'El día viernes 27 de Octubre, se llevó a cabo el Taller de Vocabularios Controlados y representación de significados en Salud. El taller se desarrollo en el Colegio Médico de Neuquén en el marco del proyecto ANDES y estuvo a cargo del Lic. Marcelo D. Carrascal, Jefe del Dto de Tecnologías de la Información del Hospital Castro Rendón. El objetivo del taller fue capacitar a profesionales de distintas especialidades en la utilización de SNOMED-CT, nomenclatura sistematizada de términos de medicina y terminología clínica. Dicha herramienta es la terminología de salud científicamente validad y más extensa del mundo. Permite la representación de conceptos de salud en forma consistente y procesable lo que la hace una herramienta excepcional para trabajar sobre registros electrónicos de salud. Implementada en aplicaciones de software, SNOMED-CT es utilizada para representar información de salud relevante en forma consistente. Provee una forma estandarizada de representar los conceptos de salud ingresados por los miembros del equipo y permite su interpretación automática a través de sistemas de validación y un vocabulario controlado semanticamente muy rico. En el taller, el primero de una serie de encuentros a realizarse en los próximos meses, participaron médicos, enfermeros, odontólogos y técnicos representando a la Zona 4, Zona Metropolitana, Hospital Castro Rendón, Direccion Provincial de Información Sanitaria entre otras. SNOMED-CT está próximo a ser incorporado como estándar nacional en los sistemas de registros electrónicos de salud. El proyecto ANDES incorpora SNOMED desde su concepción por lo que ya se ha empezado con la capacitación en su utilización.',
        categoria: 'mejora',
        fechaPublicacion: '27-09-2019',
        modulo: 'RUP',
        estado: true,
    },
    {
        id: 3515125,
        titulo: 'Se capacitó a personal perteneciente a efectores de la Zona Metro',
        bajada: 'La capacitación se realizó en el auditorio del Ministerio de Salud y fue orientada a representantes de cada efector de Zona Metro.',
        imagen: [
            'https://www.urban.org/sites/default/files/styles/optimized_default/public/gettyimages-hands-ra.jpg',
            'https://cdn2.f-cdn.com/contestentries/1461068/3980988/5c278c3d00512_thumb900.jpg',
            'https://www.daslatalla.com/wp-content/uploads/2019/07/shutterstock_517390705-1050x600.jpg',
        ],
        nota: 'El Lunes 9 de este mes se brindó una capacitación destinada a efectores de la Zona Metro en el auditorio del Ministerio de Salud. La jornada, desarrollada en el marco de la implementación del proyecto ANDES, estuvo orientada a representantes de cada centro de salud de la zona y fue asistida por Alejandra Garcia y Alejandro Ojeda, coordinadores de zona metro de Gestión de pacientes.Durante la actividad, se recorrió todo el proceso que involucra CITAS (Centro Inteligente de Trámites de Acceso a la Salud), desde la planificación de agendas hasta la revisión, codificación y otorgamiento de turnos.De esta manera, los asistentes pudieron despejar dudas y trasladar las funcionalidades de esta herramienta a su trabajo diario a través de ejemplos prácticos.',
        categoria: 'importante',
        fechaPublicacion: '29-03-2019',
        modulo: 'TOP',
        estado: true,
    },
    {
        id: 1561563,
        titulo: 'Titulo de tercera noticia',
        bajada: 'Esta es la bajada de la nota, un texto que da una primera percepcion al lector',
        imagen: [
            'https://www.rionegro.com.ar/wp-content/uploads/documents/1/0/image_content_9467211_20180316211557.jpg?w=920&h=520&crop=1',
            'https://cdn2.f-cdn.com/contestentries/1461068/3980988/5c278c3d00512_thumb900.jpg',
            'https://www.daslatalla.com/wp-content/uploads/2019/07/shutterstock_517390705-1050x600.jpg',
        ],
        nota: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi.',
        categoria: 'novedad',
        fechaPublicacion: '13-01-2019',
        modulo: 'MPI',
        estado: true,
    },
    {
        id: 1563513,
        titulo: 'Se realizó el primer taller de vocabularios controlados de Salud',
        bajada: 'Fue dirigida a miembros de equipos de salud de las distintas zonas sanitarias de la provincia.',
        imagen: [
            'http://iconocsgroup.com/wp-content/uploads/2017/02/ehealth.png',
            'https://cdn2.f-cdn.com/contestentries/1461068/3980988/5c278c3d00512_thumb900.jpgg',
            'https://miro.medium.com/max/1600/1*6jHfGiyWLiks_i5iU1tOhw.jpeg',
        ],

        nota: 'El día viernes 27 de Octubre, se llevó a cabo el Taller de Vocabularios Controlados y representación de significados en Salud. El taller se desarrollo en el Colegio Médico de Neuquén en el marco del proyecto ANDES y estuvo a cargo del Lic. Marcelo D. Carrascal, Jefe del Dto de Tecnologías de la Información del Hospital Castro Rendón. El objetivo del taller fue capacitar a profesionales de distintas especialidades en la utilización de SNOMED-CT, nomenclatura sistematizada de términos de medicina y terminología clínica. Dicha herramienta es la terminología de salud científicamente validad y más extensa del mundo. Permite la representación de conceptos de salud en forma consistente y procesable lo que la hace una herramienta excepcional para trabajar sobre registros electrónicos de salud. Implementada en aplicaciones de software, SNOMED-CT es utilizada para representar información de salud relevante en forma consistente. Provee una forma estandarizada de representar los conceptos de salud ingresados por los miembros del equipo y permite su interpretación automática a través de sistemas de validación y un vocabulario controlado semanticamente muy rico. En el taller, el primero de una serie de encuentros a realizarse en los próximos meses, participaron médicos, enfermeros, odontólogos y técnicos representando a la Zona 4, Zona Metropolitana, Hospital Castro Rendón, Direccion Provincial de Información Sanitaria entre otras. SNOMED-CT está próximo a ser incorporado como estándar nacional en los sistemas de registros electrónicos de salud. El proyecto ANDES incorpora SNOMED desde su concepción por lo que ya se ha empezado con la capacitación en su utilización.',
        categoria: 'mejora',
        fechaPublicacion: '27-11-2018',
        modulo: 'RUP',
        estado: true,
    },
    {
        id: 3515125,
        titulo: 'Se capacitó a personal perteneciente a efectores de la Zona Metro',
        bajada: 'La capacitación se realizó en el auditorio del Ministerio de Salud y fue orientada a representantes de cada efector de Zona Metro.',
        imagen: [
            'https://www.itu.int/en/ITU-D/ICT-Applications/PublishingImages/Digital-Health/Header/e-health-strategies-home-page-test.png',
            'https://cdn2.f-cdn.com/contestentries/1461068/3980988/5c278c3d00512_thumb900.jpg',
            'https://www.daslatalla.com/wp-content/uploads/2019/07/shutterstock_517390705-1050x600.jpg',
        ],
        nota: 'El Lunes 9 de este mes se brindó una capacitación destinada a efectores de la Zona Metro en el auditorio del Ministerio de Salud. La jornada, desarrollada en el marco de la implementación del proyecto ANDES, estuvo orientada a representantes de cada centro de salud de la zona y fue asistida por Alejandra Garcia y Alejandro Ojeda, coordinadores de zona metro de Gestión de pacientes.Durante la actividad, se recorrió todo el proceso que involucra CITAS (Centro Inteligente de Trámites de Acceso a la Salud), desde la planificación de agendas hasta la revisión, codificación y otorgamiento de turnos.De esta manera, los asistentes pudieron despejar dudas y trasladar las funcionalidades de esta herramienta a su trabajo diario a través de ejemplos prácticos.',
        categoria: 'importante',
        fechaPublicacion: '19-09-2018',
        modulo: 'TOP',
        estado: true,
    },
    {
        id: 1561563,
        titulo: 'Titulo de tercera noticia',
        bajada: 'Esta es la bajada de la nota, un texto que da una primera percepcion al lector',
        imagen: [
            'https://ui.andes.gob.ar/assets/img/homepage/andes-home-banner.jpg',
            'https://cdn2.f-cdn.com/contestentries/1461068/3980988/5c278c3d00512_thumb900.jpg',
            'https://ticsalutsocial.cat/wp-content/uploads/2018/03/mhealth.jpg',
        ],
        nota: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi.',
        categoria: 'novedad',
        fechaPublicacion: '07-10-2017',
        modulo: 'MPI',
        estado: true,
    },
];