import { Problema } from '../modelos/problema';


export const PROBLEMAS: Problema[] = [
    {
        id: 209,
        evolucion: "Tensión arterial dentro de los valores de referencia. T.A baja: 96, alta: 125 mmHg.",
        valor: "96/125 mmHg",
        esDiagnosticoPrincipal: true,
        semanticTag: "trastorno",
        icono: "trastorno",
        color: "danger",
        term: "Hipertensión Arterial",
        fecha: "27/01/2021",
        estado: true,
    },
    {
        id: 210,
        evolucion: "El paciente se presenta con dolor agudo en la zona del abdomen",
        valor: "37,5º",
        esDiagnosticoPrincipal: true,
        semanticTag: "trastorno",
        icono: "trastorno",
        color: "danger",
        term: "lesión traumática del abdomen",
        fecha: "27/01/2021",
        estado: true,
    },
    {
        id: 211,
        evolucion: "El paciente presenta signos y síntomas frecuentes de la alergia a la penicilina: urticaria, sarpullido y picazón",
        valor: "125 mm",
        esDiagnosticoPrincipal: true,
        semanticTag: "hallazgo",
        icono: "lupa-ojo",
        color: "warning",
        term: "Alergia A Penicilina",
        fecha: "11/09/2020",
        estado: false,
    },
    {
        id: 212,
        evolucion: "La temperatura del paciente asciende a los 38º",
        valor: "Fuera de valor de referencia",
        esDiagnosticoPrincipal: false,
        semanticTag: "trastorno",
        icono: "trastorno",
        color: "danger",
        term: "Fiebre Q",
        fecha: "27/01/2021",
        estado: false,
    },
    {
        id: 213,
        evolucion: "El paciente presenta intoleracia a los dulces",
        valor: "Fuera de valor de referencia",
        esDiagnosticoPrincipal: false,
        semanticTag: "trastorno",
        icono: "trastorno",
        color: "danger",
        term: "Diabetes Mellitus Tipo 2",
        fecha: "27/01/2021",
        estado: true,
    },
    {
        id: 214,
        evolucion: "paciente refiere disnea que se intensifica con el esfuerzo. Presencia de sibilancias autoescuchadas durante la noche. Tos, No presenta historia de alergias. Antecedentes familiar de Asma. Durante los ultimos dias presenta fiebre que no cede 38º. Mucosidad serosa",
        valor: "38º",
        esDiagnosticoPrincipal: true,
        semanticTag: "hallazgo",
        icono: "lupa-ojo",
        color: "warning",
        term: "Antecedente familiar de asma",
        fecha: "17/11/2021",
        estado: false,
    },
]