import { Prescripcion } from '../modelos/prescripcion';

export const PRESCRIPCIONES: Prescripcion[] = [
    {
        id: 312,
        nombre: 'Clorhidrato De Metformina 100 Mg/Ml, Solución Oral',
        nombreComercial: 'Clorhidrato De Metformina 100 Mg/Ml, Solución Oral',
        cantidad: '1 unidad',
        formaFarmaceutica: 'tabletas',
        fechaIndicacion: '13/07/2020',
        recetable: true,
        activo: true,
        indicacion: {
            horario: '12:00',
            referencia: 'antes del almuerzo',
            administracion: 'oral',
            vigencia: '6 meses',
            dosis: '20 mg',
            distribucion: ['dom', 'lun', 'mar', 'mier', 'jue', 'vie', 'sab'],
        },
        profesional: 'Molini, Walter Juan',
        organizacion: 'Hospital Provincial Neuquén - Dr. Eduardo Castro Rendón',
        servicio: 'Servicio de clínica médica',
        ambito: 'internación',
        nota: 'Indicado para paciente insulino-dependiente',
    },
    {
        id: 311,
        nombre: 'Enalapril 5 Mg/Ml, Solución Oral',
        nombreComercial: 'Enalapril',
        cantidad: '3 Envases',
        formaFarmaceutica: 'tabletas',
        fechaIndicacion: '21/12/2020',
        recetable: true,
        activo: true,
        indicacion: {
            horario: '22:00',
            referencia: 'después de la cena',
            administracion: 'oral',
            vigencia: '3 meses',
            dosis: '20 mg',
            distribucion: ['dom', 'lun', 'mar', 'mier', 'jue', 'vie', 'sab'],
        },
        profesional: 'Monteverde, María Laura',
        organizacion: 'Hospital Provincial Neuquén - Dr. Eduardo Castro Rendón',
        servicio: 'Unidad de terapia intermedia de adultos',
        ambito: 'internación',
        nota: 'Hipertensión esencial: Presión sistólica: 145 mm/Hg | Presión diastólica: 95 mm de Hg',
    },
    {
        id: 313,
        nombre: 'Salbutamol',
        nombreComercial: 'Ventolin',
        cantidad: '2 unidades',
        formaFarmaceutica: 'Inhalador',
        fechaIndicacion: '03/10/2020',
        recetable: true,
        activo: false,
        indicacion: {
            horario: '',
            referencia: 'suministro a demanda',
            administracion: 'oral',
            vigencia: '60 dias',
            dosis: '20 mg',
            distribucion: ['dom', 'lun', 'mar', 'mier', 'jue', 'vie', 'sab'],
        },
        profesional: 'Monteverde, María Laura',
        organizacion: 'Hospital Provincial Neuquén - Dr. Eduardo Castro Rendón',
        servicio: 'Unidad de terapia intermedia de adultos',
        ambito: 'internación',
        nota: 'El paciente presenta 3 episodios por día',
    },
    {
        id: 315,
        nombre: 'Carboximaltosa férrica',
        nombreComercial: 'Sulfato Ferroso 200 mg',
        cantidad: '4 unidades',
        formaFarmaceutica: 'Inyectable',
        fechaIndicacion: '27/11/2020',
        recetable: true,
        activo: true,
        indicacion: {
            horario: '',
            referencia: 'entre comidas',
            administracion: 'intravenosa',
            vigencia: 'durante 30 días',
            dosis: '300 mg diarios',
            distribucion: ['dom', 'lun', 'mar', 'mier', 'jue', 'vie', 'sab'],
        },
        profesional: 'Rinaldi, Paula Micaela',
        organizacion: 'Hospital de San Martín de los Andes - Dr. Ramón Carrillo',
        servicio: 'Unidad de terapia intermedia de adultos',
        ambito: 'internación',
        nota: 'el paciente presenta un cuadro anémico leve',
    },
    {
        id: 319,
        nombre: 'Carbamazepina',
        nombreComercial: 'Tegretol 200 mg',
        cantidad: '3 unidades',
        formaFarmaceutica: 'Tabletas',
        fechaIndicacion: '11/05/2019',
        recetable: true,
        activo: false,
        indicacion: {
            horario: '',
            referencia: 'despues de las comidas',
            administracion: 'oral',
            vigencia: 'durante 60 días',
            dosis: '500 mg',
            distribucion: ['dom', 'lun', 'mar', 'mier', 'jue', 'vie', 'sab'],
        },
        profesional: 'Reznik, Pedro Gabriel',
        organizacion: 'Hospital de Plottier',
        servicio: 'Unidad de terapia intermedia de adultos',
        ambito: 'internación',
        nota: 'El paciente presenta 1 episodios por día',
    },
];
