import { Card } from '../modelos/card';

export const CARDS: Card[] = [
    {
        id: 1,
        nombre: 'huds',
        tipo: 'info',
        icono: 'historial',
        path: 'miHuds',
        color: '',
        outlet: 'listado',
    },
    {
        id: 2,
        nombre: 'consultas',
        tipo: 'custom',
        icono: 'mano-corazon',
        path: 'misConsultas',
        color: '#00a4dc',
        outlet: 'listado',
    },
    {
        id: 3,
        nombre: 'problemas',
        tipo: 'custom',
        icono: 'trastorno',
        path: 'misProblemas',
        color: '#ed5a24',
        outlet: 'listado',
    },
    {
        id: 4,
        nombre: 'observaciones',
        tipo: 'custom',
        icono: 'lupa-ojo',
        path: 'misObservaciones',
        color: '#ff8922',
        outlet: 'listado',
    },
    {
        id: 5,
        nombre: 'prácticas',
        tipo: 'custom',
        icono: 'termometro',
        path: 'misLaboratorios',
        color: '#d105d1',
        outlet: 'listado',
    },
    {
        id: 6,
        nombre: 'prescripciones',
        tipo: 'custom',
        icono: 'pildoras',
        path: 'misPrescripciones',
        color: '#00cab6',
        outlet: 'listado',
    },
    {
        id: 7,
        nombre: 'laboratorios',
        tipo: 'custom',
        icono: 'pipeta',
        path: 'misLaboratorios',
        color: '#e91e79',
        outlet: 'listado',
    },
    {
        id: 8,
        nombre: 'vacunas',
        tipo: 'custom',
        icono: 'vacuna',
        path: 'misVacunas',
        color: '#5cb45c',
        outlet: 'listado',
    },
    {
        id: 10,
        nombre: 'relaciones',
        tipo: 'info',
        icono: 'familia',
        path: 'misFamiliares',
        color: '',
        outlet: 'listado',
    },
    {
        id: 11,
        nombre: 'documentos',
        tipo: 'info',
        icono: 'documento-cursor',
        path: 'misLaboratorios',
        color: '',
        outlet: 'listado',
    },
    {
        id: 12,
        nombre: 'turnos',
        tipo: 'info',
        icono: 'turno-bold',
        path: 'misTurnos',
        color: '',
        outlet: 'listado',
    },
    {
        id: 13,
        nombre: 'mensajes',
        tipo: 'info',
        icono: 'mail',
        path: 'misLaboratorios',
        color: '',
        outlet: 'listado',
    },
    {
        id: 14,
        nombre: 'organizaciones',
        tipo: 'info',
        icono: 'hospital',
        path: 'misOrganizaciones',
        color: '',
        outlet: 'listado',
    },
    {
        id: 9,
        nombre: 'equipo de salud',
        tipo: 'info',
        icono: 'medico',
        path: 'miEquipo',
        color: '',
        outlet: 'listado',
    },
    {
        id: 15,
        nombre: 'derivaciones',
        tipo: 'info',
        icono: 'hombre-caminando',
        path: 'misLaboratorios',
        color: '',
        outlet: 'listado',
    },
]
