import { Paciente } from '../modelos/paciente';

export const PACIENTES: Paciente[] = [
    {
        id: 1,
        documento: '36307632',
        cuil: '20-36307632-5',
        activo: true,
        estado: 'temporal',
        nombre: 'Nombre completo',
        apellido: 'Apellido',
        nombreCompleto: 'Nombre y Apellido',
        alias: '',
        contacto: 2993420134,
        sexo: 'femenino',
        genero: 'femenino',
        fechaNacimiento: '20/09/1992',
        tipoIdentificacion: '',
        numeroIdentificacion: '',
        edad: 27,
        edadReal: 'null',
        fechaFallecimiento: null,
        domicilio: 'Avenida San Juan 798',
        estadoCivil: undefined,
        foto: 'https://library.kissclipart.com/20180901/krw/kissclipart-user-thumbnail-clipart-user-lorem-ipsum-is-simply-bfcb758bf53bea22.jpg',
        relaciones: 'hermana',
        financiador: 'HOSPITAL PROVINCIAL NEUQUEN - CASTRO RENDON',
        identificadores: 'HOSPITAL PROVINCIAL NEUQUEN - CASTRO RENDON',
        claveBlocking: 'null',
        entidadesValidadoras: 'HOSPITAL PROVINCIAL NEUQUEN - CASTRO RENDOM',
        scan: 'null',
        reportarError: false,
        notaError: '',
    },
    {
        id: 2,
        documento: '21532632',
        cuil: '20-21532632-5',
        activo: true,
        estado: 'validado',
        nombre: 'Pedro Ernesto',
        apellido: 'Martinez Valenzuela',
        nombreCompleto: '',
        alias: '',
        contacto: 2993420134,
        sexo: 'masculino',
        genero: 'masculino',
        fechaNacimiento: '11/09/1975',
        tipoIdentificacion: '',
        numeroIdentificacion: '',
        edad: 63,
        edadReal: 'null',
        fechaFallecimiento: '20/01/2020',
        domicilio: 'Avenida San Juan 798',
        estadoCivil: undefined,
        foto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6kC2G5mah771aAk-RG2zh10844QBCW9NHkZhE8zofvVkB_wAA&s',
        relaciones: 'padre',
        financiador: 'ISSN',
        identificadores: 'null',
        claveBlocking: 'null',
        entidadesValidadoras: 'ISSN',
        scan: 'null',
        reportarError: false,
        notaError: '',
    },
    {
        id: 3,
        documento: '36307632',
        cuil: '20-36307632-5',
        activo: true,
        estado: 'temporal',
        nombre: 'Fernanda Agustina',
        apellido: 'Sastre Maranelli',
        nombreCompleto: 'Fernanda Agustina Sastre Maranelli',
        alias: '',
        contacto: 2993420134,
        sexo: 'femenino',
        genero: 'femenino',
        fechaNacimiento: '20/09/1992',
        tipoIdentificacion: '',
        numeroIdentificacion: '',
        edad: 27,
        edadReal: 'null',
        fechaFallecimiento: null,
        domicilio: 'Avenida San Juan 798',
        estadoCivil: undefined,
        foto: 'https://library.kissclipart.com/20180901/krw/kissclipart-user-thumbnail-clipart-user-lorem-ipsum-is-simply-bfcb758bf53bea22.jpg',
        relaciones: 'hermana',
        financiador: 'ISSN',
        identificadores: 'null',
        claveBlocking: 'null',
        entidadesValidadoras: 'ISSN',
        scan: 'null',
        reportarError: false,
        notaError: '',
    },
    {
        id: 4,
        documento: '12532632',
        cuil: '20-12532632-5',
        activo: true,
        estado: 'validado',
        nombre: 'Mariela Alejandra',
        apellido: 'Valenzuela Della Gaspera',
        nombreCompleto: '',
        alias: '',
        contacto: 2993420134,
        sexo: 'femenino',
        genero: 'femenino',
        fechaNacimiento: '20/09/1957',
        tipoIdentificacion: '',
        numeroIdentificacion: '',
        edad: 63,
        edadReal: 'null',
        fechaFallecimiento: null,
        domicilio: 'Avenida San Juan 798',
        estadoCivil: undefined,
        foto: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbBtcp6GJRRRgLnNyIAlDH1KM8M6YDARj44i-W_Mhisw37HiJosQ&s',
        relaciones: 'hermana',
        financiador: 'ISSN',
        identificadores: 'null',
        claveBlocking: 'null',
        entidadesValidadoras: 'ISSN',
        scan: 'null',
        reportarError: false,
        notaError: '',
    },
    {
        id: 5,
        documento: '36307632',
        cuil: '20-36307632-5',
        activo: true,
        estado: 'temporal',
        nombre: 'Agustina Alejandra',
        apellido: 'Jara Martino',
        nombreCompleto: 'Fernanda Agustina Sastre Maranelli',
        alias: '',
        contacto: 2993420134,
        sexo: 'femenino',
        genero: 'femenino',
        fechaNacimiento: '20/09/1992',
        tipoIdentificacion: '',
        numeroIdentificacion: '',
        edad: 27,
        edadReal: 'null',
        fechaFallecimiento: null,
        domicilio: 'Avenida San Juan 798',
        estadoCivil: undefined,
        foto: 'https://library.kissclipart.com/20180901/krw/kissclipart-user-thumbnail-clipart-user-lorem-ipsum-is-simply-bfcb758bf53bea22.jpg',
        relaciones: 'prima',
        financiador: 'ISSN',
        identificadores: 'null',
        claveBlocking: 'null',
        entidadesValidadoras: 'ISSN',
        scan: 'null',
        reportarError: false,
        notaError: '',
    },
    {
        id: 6,
        documento: '38906735',
        cuil: '20-38906735-5',
        activo: true,
        estado: 'temporal',
        nombre: 'Marco Savino',
        apellido: 'Santarelli',
        nombreCompleto: '',
        alias: '',
        contacto: 2993420134,
        sexo: 'masculino',
        genero: 'masculino',
        fechaNacimiento: '20/09/1957',
        tipoIdentificacion: '',
        numeroIdentificacion: '',
        edad: 63,
        edadReal: 'null',
        fechaFallecimiento: null,
        domicilio: 'Las acacias 410',
        estadoCivil: undefined,
        foto: 'https://library.kissclipart.com/20180901/krw/kissclipart-user-thumbnail-clipart-user-lorem-ipsum-is-simply-bfcb758bf53bea22.jpg',
        relaciones: 'abuelo',
        financiador: 'ISSN',
        identificadores: 'null',
        claveBlocking: 'null',
        entidadesValidadoras: 'ISSN',
        scan: 'null',
        reportarError: false,
        notaError: '',
    }
];
