import { ICard } from './interfaces/icard';

export const CARDS: ICard[] = [
    {
        id: 1,
        nombre: 'huds',
        tipo: 'info',
        semanticTag: 'solicitud',
        icono: 'historial',
        path: 'mi-huds',
        color: '#0070cc',
        outlet: 'listado',
    },
    {
        id: 2,
        nombre: 'consultas',
        tipo: 'custom',
        semanticTag: 'solicitud',
        icono: 'mano-corazon',
        path: 'mis-consultas',
        color: '#0070cc',
        outlet: 'listado',
    },
    {
        id: 3,
        nombre: 'problemas',
        tipo: 'custom',
        semanticTag: 'trastorno',
        icono: 'trastorno',
        path: '',
        color: '#ff4a1a',
        outlet: 'listado',
    },
    {
        id: 4,
        nombre: 'observaciones',
        tipo: 'custom',
        semanticTag: 'hallazgo',
        icono: 'lupa-ojo',
        path: 'mis-problemas',
        color: '#f4a03b',
        outlet: 'listado',
    },
    {
        id: 5,
        nombre: 'prácticas',
        tipo: 'custom',
        semanticTag: 'procedimiento',
        icono: 'termometro',
        path: 'mis-laboratorios',
        color: '#92278e',
        outlet: 'listado',
    },
    {
        id: 6,
        nombre: 'prescripciones',
        tipo: 'custom',
        semanticTag: 'producto',
        icono: 'pildoras',
        path: '',
        color: '#00bcb4',
        outlet: 'listado',
    },
    {
        id: 7,
        nombre: 'laboratorios',
        tipo: 'custom',
        semanticTag: 'laboratorio',
        icono: 'recipiente',
        path: 'mis-laboratorios',
        color: '#a0a0a0',
        outlet: 'listado',
    },
    {
        id: 8,
        nombre: 'vacunas',
        tipo: 'custom',
        semanticTag: 'procedimiento',
        icono: 'vacuna',
        path: 'mis-vacunas',
        color: '#92278e',
        outlet: 'listado',
    },
    {
        id: 10,
        nombre: 'relaciones',
        tipo: 'info',
        semanticTag: 'solicitud',
        icono: 'familia',
        path: 'mis-familiares',
        color: '#0070cc',
        outlet: 'listado',
    },
    {
        id: 11,
        nombre: 'documentos',
        tipo: 'info',
        semanticTag: 'registro',
        icono: 'documento-cursor',
        path: 'mis-documentos',
        color: '#0070cc',
        outlet: 'listado',
    },
    {
        id: 12,
        nombre: 'turnos',
        tipo: 'info',
        semanticTag: 'solicitud',
        icono: 'turno-bold',
        path: 'mis-turnos',
        color: '#0070cc',
        outlet: 'listado',
    },
    {
        id: 13,
        nombre: 'mensajes',
        tipo: 'info',
        semanticTag: 'otro',
        icono: 'mail',
        path: 'mis-mensajes',
        color: '#0070cc',
        outlet: 'listado',
    },
    {
        id: 14,
        nombre: 'organizaciones',
        tipo: 'info',
        semanticTag: 'solicitud',
        icono: 'hospital',
        path: 'mis-organizaciones',
        color: '#0070cc',
        outlet: 'listado',
    },
    {
        id: 9,
        nombre: 'equipo de salud',
        tipo: 'info',
        semanticTag: 'solicitud',
        icono: 'medico',
        path: 'mi-equipo',
        color: '#0070cc',
        outlet: 'listado',
    },
    {
        id: 15,
        nombre: 'derivaciones',
        tipo: 'info',
        semanticTag: 'solicitud',
        icono: 'avion',
        path: 'mis-solicitudes',
        color: '#0070cc',
        outlet: 'listado',
    },
];
