name: PORTAL BUILD AND TEST
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - run: npm ci
            - run: npm run lint
            - run: rm browserslist && touch browserslist
            - run: npm run portal:build:prod -- --progress=false
